[lib]
crate-type = ["cdylib"]

[package]
name = "wasm"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2"
meval = "0.2"
web-sys = { version = "0.3", features = ["console"] } 
evalexpr = "10.0"